export {
  adjacentNTuples,
  adjacentPairs,
  allElementsAreInstances,
  batchByProperty,
  concatenateLists,
  listDifferenceUpdate,
  listUpdate,
  listify,
  tuplify,
  makeEven,
  makeEvenByCycling,
  removeListRedundancies,
  removeNones,
  resizeArray,
  resizePreservingOrder,
  resizeWithInterpolation,
  stretchArrayToLength,
  uniqChain,
  hashObj,
} from "./iterables.js";
