/**
 * Tests that verify our math functions match Python Manim's output.
 * Golden data generated by scripts/generate-golden-data.py
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";
import "../../helpers/point-matchers.js";
import {
  smooth,
  smoothstep,
  doubleSmooth,
  bezier,
  np,
  rotateVector,
  OUT,
  PI,
} from "../../../src/core/math/index.js";

const GOLDEN_DIR = join(__dirname, "../../golden-data");

function loadGolden(name: string) {
  return JSON.parse(readFileSync(join(GOLDEN_DIR, name), "utf-8"));
}

describe("golden: rate functions", () => {
  const data = loadGolden("rate-functions.json");
  const tValues: number[] = data.t_values;

  it("smooth matches Python at all sample points", () => {
    const expected: number[] = data.functions.smooth;
    for (let i = 0; i < tValues.length; i++) {
      expect(smooth(tValues[i])).toBeCloseTo(expected[i], 6);
    }
  });

  it("smoothstep matches Python at all sample points", () => {
    const expected: number[] = data.functions.smoothstep;
    for (let i = 0; i < tValues.length; i++) {
      expect(smoothstep(tValues[i])).toBeCloseTo(expected[i], 6);
    }
  });

  it("doubleSmooth matches Python at all sample points", () => {
    const expected: number[] = data.functions.double_smooth;
    for (let i = 0; i < tValues.length; i++) {
      expect(doubleSmooth(tValues[i])).toBeCloseTo(expected[i], 6);
    }
  });
});

describe("golden: bezier evaluation", () => {
  const data = loadGolden("bezier.json");

  for (const sample of data.samples) {
    describe(sample.name, () => {
      const controlPoints = sample.controlPoints.map(
        (p: number[]) => np.array([p[0], p[1], p[2]])
      );
      const fn = bezier(controlPoints);

      for (let i = 0; i < sample.t_values.length; i++) {
        const t = sample.t_values[i];
        const expected = sample.results[i];

        it(`at t=${t}`, () => {
          const result = fn(t).toArray() as number[];
          expect(result[0]).toBeCloseTo(expected[0], 8);
          expect(result[1]).toBeCloseTo(expected[1], 8);
          expect(result[2]).toBeCloseTo(expected[2], 8);
        });
      }
    });
  }
});

describe("golden: rotation", () => {
  const data = loadGolden("rotation.json");

  for (const c of data.cases) {
    it(`${c.name}: rotate [${c.point}] by ${(c.angle / PI * 180).toFixed(0)}° around [${c.axis}]`, () => {
      const axis = np.array([c.axis[0], c.axis[1], c.axis[2]]);
      const point = np.array([c.point[0], c.point[1], c.point[2]]);
      const result = rotateVector(point, c.angle, axis);
      const r = result.toArray() as number[];
      expect(r[0]).toBeCloseTo(c.result[0], 6);
      expect(r[1]).toBeCloseTo(c.result[1], 6);
      expect(r[2]).toBeCloseTo(c.result[2], 6);
    });
  }
});
